# Classification metrics

In [1]:
from sklearn import metrics
import numpy as np

def class_metrics(actual, predicted, binary=True):
    conf_mat = metrics.confusion_matrix(actual, predicted)
    avg_acc = metrics.accuracy_score(actual, predicted)
    cosine_sim = metrics.pairwise.cosine_similarity(np.array(actual).reshape(1, -1), np.array(predicted).reshape(1, -1))
    print(f'confusion matrix : \n{conf_mat}')
    print(f'cosine similarity : {cosine_sim}')
    print(f'average accuracy : {avg_acc}')
    if binary:
        precision = metrics.precision_score(actual, predicted)
        recall = metrics.recall_score(actual, predicted)
        f1 = metrics.f1_score(actual, predicted)
        print(f'precision : {precision}')
        print(f'recall : {recall}')
        print(f'f1-score : {f1}')
    else:
        micro_prec = metrics.precision_score(actual, predicted, average='micro')
        micro_recall = metrics.recall_score(actual, predicted, average='micro')
        micro_f1 = metrics.f1_score(actual, predicted, average='micro')
        macro_prec = metrics.precision_score(actual, predicted, average='macro')
        macro_recall = metrics.recall_score(actual, predicted, average='macro')
        macro_f1 = metrics.f1_score(actual, predicted, average='macro')
        print(f'micro precision : {micro_prec}')
        print(f'micro recall : {micro_recall}')
        print(f'micro f1 : {micro_f1}')
        print(f'macro precision : {macro_prec}')
        print(f'macro recall : {macro_recall}')
        print(f'macro f1 : {macro_f1}') 

In [2]:
actual = [1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4]
predicted = [1, 1, 1, 2, 3, 2, 3, 1, 3, 4, 2, 3]
class_metrics(actual, predicted, binary=False)

confusion matrix : 
[[2 0 0 0]
 [1 1 1 0]
 [1 1 2 0]
 [0 1 1 1]]
cosine similarity : [[0.94324222]]
average accuracy : 0.5
micro precision : 0.5
micro recall : 0.5
micro f1 : 0.5
macro precision : 0.5833333333333333
macro recall : 0.5416666666666666
macro f1 : 0.5


In [3]:
actual = [0, 1, 1, 0, 0, 0, 1, 1, 0, 0]
predicted = [1, 1, 1, 1, 0, 0, 1, 0, 0, 1]
class_metrics(actual, predicted, binary=True)

confusion matrix : 
[[3 3]
 [1 3]]
cosine similarity : [[0.61237244]]
average accuracy : 0.6
precision : 0.5
recall : 0.75
f1-score : 0.6


In [4]:
actual = [1, 0, 1, 1, 0]
predictedA = [1, 1, 1, 0, 0]
predictedB = [0, 0, 0, 1, 1]
class_metrics(actual, predictedA, binary=True)
class_metrics(actual, predictedB, binary=True)

confusion matrix : 
[[1 1]
 [1 2]]
cosine similarity : [[0.66666667]]
average accuracy : 0.6
precision : 0.6666666666666666
recall : 0.6666666666666666
f1-score : 0.6666666666666666
confusion matrix : 
[[1 1]
 [2 1]]
cosine similarity : [[0.40824829]]
average accuracy : 0.4
precision : 0.5
recall : 0.3333333333333333
f1-score : 0.4


# Similarity

### Cosine similarity

$$sim_{cos}(x,y) = \frac{\mathbf{x} \cdot \mathbf{y}}{||\mathbf{x}||~||\mathbf{y}||} = \frac{\sum_{i=1}^n x_i y_i}{\sqrt{\sum_{i=1}^n x_i^2} \sqrt{\sum_{i=1}^n y_i^2}}$$

## Jaccard similarity

This metric is a set similarity; that is, it only captures the presence and absence of terms with no regard to their frequency. Put simply, it captures the ratio of shared terms and total terms in the two documents.

$$sim_{Jaccard} = \frac{|X \cap Y|}{|X \cup Y|}$$

In [5]:
import math

def jaccard(x, y):
    """Computes the Jaccard similarity between two term vectors."""
    num_both = 0
    num_either = 0
    for xi, yi in zip(x, y):
        num_both += int(xi > 0 and yi > 0)
        num_either += int(xi > 0 or yi > 0)
    return num_both / num_either

def cosine(x, y):
    """Computes the Cosine similarity between two term vectors."""
    dot_product = 0
    x_len = 0
    y_len = 0
    for xi, yi in zip(x, y):
        dot_product += xi * yi
        x_len += xi ** 2
        y_len += yi ** 2
        
    return dot_product / (math.sqrt(x_len) * math.sqrt(y_len))

In [6]:
actual = [1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4]
predicted = [1, 1, 1, 2, 3, 2, 3, 1, 3, 4, 2, 3]
j = jaccard(actual, predicted)
c = cosine(actual, predicted)
print(f'cosine similarity : {c}')
print(f'jaccard similarity : {j}')

cosine similarity : 0.9432422182837985
jaccard similarity : 1.0


# Text preprocessing

In [7]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [8]:
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()
sentence = '''
Two fathers and two sons went fishing They saw a tall and strong tree 
reaching high into the heavens for all the world to see They spent three 
hours there before heading home'''
stemmed = ' '.join(stemmer.stem(word) for word in sentence.split())
print(stemmed)

two father and two son went fish they saw a tall and strong tree reach high into the heaven for all the world to see they spent three hour there befor head home


# Document classifier

Create term/document or term/class matrix and compute.

## Indexing

* lowercase
* vocabulary according to stopwords
* suffix-s stemming
* posting lists for docs
* frequency information

# Retrieval evaluation

## Binary relevance

In [10]:
def evaluate_binary(rankings, ground_truth):
    sum_p5, sum_p10, sum_ap, sum_rr = 0, 0, 0, 0

    for qid, ranking in sorted(rankings.items()):
        gt = gtruth[qid]    
        print("Query", qid, "\n\tranking:", ranking, "\n\tground truth:", gt)

        p5, p10, ap, rr, num_rel = 0, 0, 0, 0, 0

        for i, doc_id in enumerate(ranking):
            if doc_id in gt:  # doc is relevant
                num_rel += 1  
                pi = num_rel / (i + 1)  # P@i
                ap += pi  # AP

                if i < 5:  # P@5
                    p5 += 1
                if i < 10:  # P@10
                    p10 += 1
                if rr == 0:  # Reciprocal rank
                    rr = 1 / (i + 1)

        p5 /= 5
        p10 /= 10
        ap /= len(gt)  # divide by the number of relevant documents
        print("\tP@5:", round(p5, 3), "\n\tP@10:", round(p10, 3), "\n\tAP:", round(ap, 3), "\n\tRR:", round(rr, 3))


        sum_p5 += p5
        sum_p10 += p10
        sum_ap += ap
        sum_rr += rr

    print("Average")
    print("\tP@5:", round(sum_p5 / len(rankings), 3), "\n\tP@10:", round(sum_p10 / len(rankings), 3), 
          "\n\tMAP:", round(sum_ap / len(rankings), 3), "\n\tMRR:", round(sum_rr / len(rankings), 3))

In [11]:
rankings = {
    "q1": [1, 2, 4, 5, 3, 6, 9, 8, 10, 7],
    "q2": [1, 2, 4, 5, 3, 9, 8, 6, 10, 7],
    "q3": [1, 7, 4, 5, 3, 6, 9, 8, 10, 2]
}

gtruth = {
    "q1": [1, 3],
    "q2": [2, 4, 5, 6],
    "q3": [7]
}

evaluate_binary(rankings, gtruth)

Query q1 
	ranking: [1, 2, 4, 5, 3, 6, 9, 8, 10, 7] 
	ground truth: [1, 3]
	P@5: 0.4 
	P@10: 0.2 
	AP: 0.7 
	RR: 1.0
Query q2 
	ranking: [1, 2, 4, 5, 3, 9, 8, 6, 10, 7] 
	ground truth: [2, 4, 5, 6]
	P@5: 0.6 
	P@10: 0.4 
	AP: 0.604 
	RR: 0.5
Query q3 
	ranking: [1, 7, 4, 5, 3, 6, 9, 8, 10, 2] 
	ground truth: [7]
	P@5: 0.2 
	P@10: 0.1 
	AP: 0.5 
	RR: 0.5
Average
	P@5: 0.4 
	P@10: 0.233 
	MAP: 0.601 
	MRR: 0.667


## Graded relevance

Discounted cumulative gain at rank p:
$DCG_p = rel_1 + \sum_{i=2}^p\frac{rel_i}{\log_2 i}$

Normalized discounted cumulative gain at rank p:
$NDCG_p = \frac{DCG_p}{IDCG}$

where IDCG is the DCG_p score of an idealized (perfect) ranking.

In [12]:
def dcg(rel, p):
    dcg = rel[0]
    for i in range(1, min(p, len(rel))): 
        dcg += rel[i] / math.log2(i + 1)  # rank position is indexed from 1..
    return dcg

def evaluate_graded(rankings, ground_truth):
    sum_ndcg5 = 0
    sum_ndcg10 = 0

    for qid, ranking in sorted(rankings.items()):
        gt = gtruth[qid]    
        print(f'Query {qid}')

        gains = [] # holds corresponding relevance levels for the ranked docs
        for doc_id in ranking: 
            gain = gt.get(doc_id, 0)
            gains.append(gain)
        print(f'\tGains: {gains}')

        # relevance levels of the idealized ranking
        gain_ideal = sorted([v for _, v in gt.items()], reverse=True)
        print(f'\tIdeal gains: {gain_ideal}')

        ndcg5 = dcg(gains, 5) / dcg(gain_ideal, 5)
        ndcg10 = dcg(gains, 10) / dcg(gain_ideal, 10)
        sum_ndcg5 += ndcg5
        sum_ndcg10 += ndcg10

        print(f'\tDCG@5:{dcg(gains, 5):.3f} \n\tDCG@10: {dcg(gains, 10):.3f}')
        print(f'\tNDCG@5:{ndcg5:.3f} \n\tNDCG@10: {ndcg10:.3f}')

    print('Average')
    print(f'\tNDCG@5: {sum_ndcg5 / len(rankings):.3f} \n\tNDCG@10: {sum_ndcg10 / len(rankings):.3f}')

In [13]:
rankings = {
    "q1": [2, 1, 3, 4, 5, 6, 10, 7, 9, 8],
    "q2": [1, 2, 9, 4, 5, 6, 7, 8, 3, 10],
    "q3": [1, 7, 4, 5, 3, 6, 9, 8, 10, 2]
}
gtruth = {
    "q1": {4: 3, 1: 2, 2: 1},
    "q2": {3: 3, 4: 3, 1: 2, 2: 1, 8: 1},
    "q3": {1: 3, 4: 3, 7: 2, 5: 2, 6: 1, 8: 1}
}
evaluate_graded(rankings, gtruth)

Query q1
	Gains: [1, 2, 0, 3, 0, 0, 0, 0, 0, 0]
	Ideal gains: [3, 2, 1]
	DCG@5:4.500 
	DCG@10: 4.500
	NDCG@5:0.799 
	NDCG@10: 0.799
Query q2
	Gains: [2, 1, 0, 3, 0, 0, 0, 1, 3, 0]
	Ideal gains: [3, 3, 2, 1, 1]
	DCG@5:4.500 
	DCG@10: 5.780
	NDCG@5:0.549 
	NDCG@10: 0.705
Query q3
	Gains: [3, 2, 3, 2, 0, 1, 0, 1, 0, 0]
	Ideal gains: [3, 3, 2, 2, 1, 1]
	DCG@5:7.893 
	DCG@10: 8.613
	NDCG@5:0.908 
	NDCG@10: 0.949
Average
	NDCG@5: 0.752 
	NDCG@10: 0.818


In [14]:
rankings = {
    "rA": [10, 7, 9, 8, 2, 1, 3, 4, 5, 6],
    "rB": [3, 2, 1, 4, 5, 7, 8, 10, 9, 6],
}
gtruth = {
    "rA": {1: 3, 7: 3, 2: 2, 3: 1},
    "rB": {1: 3, 7: 3, 2: 2, 3: 1}
}
evaluate_graded(rankings, gtruth)

Query rA
	Gains: [0, 3, 0, 0, 2, 3, 1, 0, 0, 0]
	Ideal gains: [3, 3, 2, 1]
	DCG@5:3.861 
	DCG@10: 5.378
	NDCG@5:0.497 
	NDCG@10: 0.693
Query rB
	Gains: [1, 2, 3, 0, 0, 3, 0, 0, 0, 0]
	Ideal gains: [3, 3, 2, 1]
	DCG@5:4.893 
	DCG@10: 6.053
	NDCG@5:0.630 
	NDCG@10: 0.780
Average
	NDCG@5: 0.564 
	NDCG@10: 0.736


# Misc

The formula for the number of handshakes possible at a party with n people is $\frac{n*(n - 1)}{2}$.
This is because each of the n people can shake hands with n - 1 people (they would not shake their own hand), and the handshake between two people is not counted twice.